#@ description: A generic profile for DIY reflow hotplates
#
# Custom profile based on some of the considerations of using a DIY, PCB-based hotplate.
# Reflow ovens apply heat from all sides - top and bottom and even on the sides of
# components. A hotplate only applies heat from the bottom, so the top of the PCB will
# be colder than the hotplate, as will the components.
# Additionally, there are practical limitations on how hot a PCB hotplate can get and
# how much power may be available to get it there.
#
# For these reasons, the following main differences are made to the JEDEC recommendations:
#
# - The soak stage is longer to allow more time for heat to soak into the components whilst
#   it also leaks out of the top of the PCB and components.
# - The soak stage ends at a higher temperature to ensure we're closer to reflow before we
#   start the ramp to peak temperature.
# - The reflow stage (ie. time above 183 celsius) is longer to allow more time for good
#   reflow and wetting of pads and terminals/leads on components. 
#

# Start a little below ambient to ensure we start in an "off" state.
- name: ambient
  seconds: 0
  temperature: 15
- name: band0-55
  seconds: 25
  temperature: 60
- name: band0-55
  seconds: 45
  temperature: 80
- name: band0-55
  seconds: 10
  temperature: 105
- name: band0-55
  seconds: 40
  temperature: 90
- name: band0-55
  seconds: 40
  temperature: 110

- name: band1-125
  seconds: 20
  temperature: 140
- name: band1-125
  seconds: 40
  temperature: 100
- name: band1-125
  seconds: 15
  temperature: 150
- name: band1-125
  seconds: 60
  temperature: 100
- name: band1-125
  seconds: 60
  temperature: 130
- name: band1-125
  seconds: 30
  temperature: 160

- name: band2-175
  seconds: 25
  temperature: 200
- name: band2-175
  seconds: 60
  temperature: 150
- name: band2-175
  seconds: 20
  temperature: 190
- name: band2-175
  seconds: 20
  temperature: 150
- name: band2-175
  seconds: 50
  temperature: 170
- name: band2-175
  seconds: 30
  temperature: 200

- name: band3-210
  seconds: 20
  temperature: 220
- name: band3-210
  seconds: 40
  temperature: 190
- name: band3-210
  seconds: 45
  temperature: 220
- name: band3-210
  seconds: 20
  temperature: 190
- name: band3-210
  seconds: 60
  temperature: 220
- name: band3-210
  seconds: 20
  temperature: 220
- name: band3-210
  seconds: 60
  temperature: 190

- name: cool
  seconds: 1
  temperature: 10
- name: cool
  seconds: 15
  temperature: 10