#@ description: Designed for lower power supplies
- name: ambient
  seconds: 0
  temperature: 25
- name: preheat
  seconds: 70
  temperature: 100
- name: soak
  seconds: 240
  temperature: 175
- name: reflow
  seconds: 90
  temperature: 220
- name: hold
  seconds: 20
  temperature: 220
- name: cool
  seconds: 180
  temperature: 100
- name: monitor
  seconds: 180
  temperature: 25
