#@ description: Designed for lower power supplies
- name: ambient
  seconds: 0
  temperature: 15
- name: preheat
  seconds: 70
  temperature: 100
- name: soak
  seconds: 120
  temperature: 150
- name: reflow
  seconds: 60
  temperature: 190
- name: reflow
  seconds: 40
  temperature: 210
- name: dwell
  seconds: 20
  temperature: 210
- name: cool
  seconds: 110
  temperature: 100
- name: off
  seconds: 1
  temperature: 15
- name: monitor
  seconds: 179
  fan: true
  temperature: 15
